config/routes.rb
Rails.application.routes.draw do

  root(to: 'static_pages#index')
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  get '/social-media-marketing', to: 'static_pages#smm', as: 'smm'
  get '/search-engine-optimization', to: 'static_pages#seo', as: 'seo'
  get '/advertising', to: 'static_pages#ppc', as: 'advertising'
  get '/special', to: 'static_pages#special', as: 'special'
  get '/dream-scenario', to: 'static_pages#dream', as: 'dream'
  get '/modern-marketing/course', to: 'static_pages#mmc', as: 'mmc'


  post '/', to: 'static_pages#create', as: "create_contact"


  get '/modern-marketing', to: 'emails#new', as: 'mm'
  post '/modern-marketing', to: 'emails#create', as: 'create_email'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates(:subject, presence: true)
  validates(:name, presence: true)

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX })
  validates(:body, presence: true)
end

app/models/email.rb
class Email < ApplicationRecord

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX })

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

  before_action :logged_in?, only: [:new]

  def index
  end

  def new
    @email = Email.new
  end

  def create
    @email = Email.new(params.require(:email).permit(:email))
    if @email.save
      session[:email_id] = @email.id
      redirect_to(mmc_path)
    else
      redirect_back(fallback_location: root_path)
      flash[:notice] = "Something went wrong. Try again."
    end
  end

  def logged_in?
    if session[:email_id]
      redirect_to(mmc_path)
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :logged_in?, only: [:mmc]
  
  def index
    @contact = Contact.new
  end

  def terms
    @contact = Contact.new
  end

  def privacy
    @contact = Contact.new
  end

  def smm
    @contact = Contact.new
  end

  def seo
    @contact = Contact.new
  end

  def ppc
    @contact = Contact.new
  end

  def special
    @contact = Contact.new
  end

  def dream
  end

  def mmc
  end

  def create
    @contact = Contact.new(params.require(:contact).permit(:name, :budget, :website, :service, :email, :subject, :body))
    if @contact.save
      flash[:success] = "Thank you. We'll get back to you asap!"
      redirect_to(root_path)
    else
      flash[:notice] = "You didn't fill in all fields correctly. Please try again."
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def logged_in?
    unless session[:email_id]
      flash[:notice] = "You must register your email first."
      redirect_to(mm_path)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConversionGetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %><span class="close" style="margin-left: 5px; cursor: pointer;">[x]</span></div>
    <% end %>
    <% if flash[:success] %>
      <div class="success"><%= flash[:success] %><span class="close" style="margin-left: 5px; cursor: pointer;">[x]</span></div>
    <% end %>
    <%= yield %>
  </body>

  <% case params[:action] %>
    <% when 'index', 'special' %>
      <%= javascript_include_tag 'fixed-header', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'smooth-scroll', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'dynamic-form', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'close', 'data-turbolinks-track': 'reload' %>
    <% when 'smm', 'seo', 'ppc' %>
      <%= javascript_include_tag 'smooth-scroll-services', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'close', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'dynamic-form', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'close', 'data-turbolinks-track': 'reload' %>
    <% when 'privacy', 'terms', 'dream' %>
      <%= javascript_include_tag 'light-smooth-scroll', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'dynamic-form', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'close', 'data-turbolinks-track': 'reload' %>
    <% when 'mmc' %>
      <%= javascript_include_tag 'collapsediv', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'close', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= javascript_include_tag 'close', 'data-turbolinks-track': 'reload' %>
  <% end %>
</html>

app/views/shared/_contactform.html.erb
<section class="grey-background" id="contact">

      <h2>CONNECT WITH US</h2>

        <div class="get-quote-container">

           <%= form_for(@contact, url: create_contact_path) do |f| %>
           
           <div class="form-field">
              <select name="contact[subject]" class="lead-select" id="select-subject"">
                <option value="" disabled selected>Select Subject</option>
                <option value="quote">Get Quote</option>
                <option value="audit">Free Audit</option>
                <option value="question">Question</option>
              </select>
            </div>

            <div class="form-field">
              <%= f.text_field(:name, class: 'input-item', placeholder: "Your name..") %>
            </div>
            <div class="form-field">
             <%= f.text_field(:email, class: 'input-item', placeholder: "Your email..") %>
            </div>
             <div class="form-field">
              <select name="contact[service]" class="input-select" id="select-service">
                <option value="" disabled selected>Select Service</option>
                <option value="smm">Social Media Marketing</option>
                <option value="seo">Search Engine Optimization</option>
                <option value="ppc">Advertising</option>
                <option value="all">All</option>
                <option value="web-dev">Web Development</option>
              </select>
            </div>

            <div class="form-field">
              <select name="contact[budget]" class="input-select" id="select-budget">
                <option value="" disabled selected>What's Your Budget?</option>
                <option value="500">$500-$1,000</option>
                <option value="1000">$1,000-$1,500</option>
                <option value="1500">$1,500-$2,000</option>
                <option value="2000">$2,000+</option>
              </select>
            </div>
            <div class="form-field">
             <%= f.text_area(:body, class: 'input-body', placeholder: "Your message..") %>
            </div>
            <div class="form-field">
             <%= f.submit("Send", class: 'submit') %>
           </div>
           <% end %>   

        </div>

        <div class="social-media-container">
          <ul>
            <li><i class="fas fa-envelope"></i></li>
            <li><i class="fab fa-facebook-square"></i></li>
            <li><i class="fab fa-instagram"></i></li>
            <li><i class="fab fa-twitter"></i></li>
          </ul>
      </div>  

    </section>

app/views/shared/_footer.html.erb
<footer>
      <div class="link-container">
        <div class="link-item">
          <h4>QUICK LINKS</h4>
          <ul>
            <li><a href="<%= root_path %>">Home</a></li>
            <li><a href="/#services">Services</a></li>
            <li><a href="/#contact">Contact</a></li>
          </ul>
        </div>
        <div class="link-item">
          <h4>SERVICES</h4>
          <ul>
            <li><a href="<%= smm_path %>">Social Media Management</a></li>
            <li><a href="<%= seo_path %>">Search-Engine-Optimization</a></li>
            <li><a href="<%= advertising_path %>">Advertising</a></li>
          </ul>
        </div>
        <div class="link-item">
          <h4>LEGAL</h4>
          <ul>
            <li><a href="<%= terms_path %>">Terms</a></li>
            <li><a href="<%= privacy_path %>">Privacy</a></li>
          </ul>
        </div>
       
      </div>
    </footer>

app/views/static_pages/dream.html.erb
  <div class="container">
      
      <header class="blue-background">
        <figure>
          <a href="<%= root_path %>"><%= image_tag("conversion-getter-logo.png") %></a>
        </figure>
        <nav>
          <ul>
            <li><a href="<%= root_path %>">HOME</a></li>
            <li><a href="/#servies">SERVICES</a></li>
            <li id="contact-link">CONTACT</li>
            <li><a href="<%= mm_path %>"><button class="m-m-btn">MODERN MARKETING</button></a></li>
            <li><button class="quote-btn">GET QUOTE</button></li>
          </ul>
        </nav>  
      </header>

      <section class="grey-background">
        <h2 style="margin:0;">To <span class="highlight">dream</span> is to imagine, let's take that journey <span class="highlight">together</span>.</h2>
      </section>

     <section class="campaign">
      <div class="campaign-container">
        <%= image_tag("imagine-us-as-a-team.png") %>
      </div>
    </section> 

    <section class="grey-background">
      <h2>We turn dreams into reality.</h2>
      <center><button class="quote-btn">GET QUOTE</button></center>
    </section>
    

    <section>
      <h2>WHY US?</h2>
      
      <div class="item-container">

        <div class="item center-item">
          <i class="fas fa-bullseye"></i>
          <h3>We Are Modern Marketers</h3>
          <p>We dive deep to understand your position in the marketplace and why people should feel the need to buy your product/service. We’re determined to cement this position of your brand in the minds of the people that you seek to serve and build the tension needed for them to take action.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-lightbulb"></i>
          <h3>We Are Innovative Marketers</h3>
          <p>We constantly seek new, better, and more efficient ways to reach the people that you seek to serve. By combining best practices and being at the forefront when it comes to the latest most innovative marketing strategies, we’ll give your brand the best opportunity to grow and reach new heights.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-heart"></i>
          <h3>We are Transparent Marketers</h3>
          <p>Our goal is to be as transparent and receptive as possible with our clients. To do that, we’ll create a marketing plan that will include the goals we agree on, the strategies we’ll use to achieve them, and the metrics we’ll use to measure the performance of our marketing efforts.</p>
        </div>

      </div>
      
    </section>

    <section class="grey-background" id="contact">

      <h2>CONNECT WITH US</h2>

      <div class="connect-container">

        <div class="button-container">
          <button class="selected">GET QUOTE</button>
          <button>GET IN TOUCH</button>
        </div>

          <div class="get-quote-container">

            <!-- Must wrap this in a form tag... -->

            <div class="form-field">
              <input class="input-item" type="text" placeholder="Your name..">
            </div>

            <div class="form-field">
              <input class="input-item" type="text" placeholder="Your Company..">
            </div>

            <div class="form-field">
              <input class="input-item" type="text" placeholder="Your email..">
            </div>

            <div class="form-field">
              <input class="input-item" type="text" placeholder="Your website..">
            </div>

            <div class="form-field">
              <select class="input-select" id="select-1">
                <option value="" disabled selected>Select Service</option>
                <option value="smm">Social Media Marketing</option>
                <option value="seo">Search Engine Optimization</option>
                <option value="ppc">Advertising</option>
                <option value="all">All</option>
                <option value="web-dev">Web Development</option>
              </select>
            </div>

            <div class="form-field">
              <select class="input-select">
                <option value="" disabled selected>What's Your Budget?</option>
                <option value="smm">$500-$1,000</option>
                <option value="seo">$1,000-$1,500</option>
                <option value="ppc">$1,500-$2,000</option>
                <option value="ppc">$2,000+</option>
              </select>
            </div>

            <div class="form-field">
              <textarea class="input-body" type="text" placeholder="Your message.."></textarea>
            </div>

            <div class="form-field">
              <button class="submit">GET QUOTE</button>
            </div>

        </div>

        <div class="get-in-touch-container">

            <div class="form-field">
              <select class="input-select" id="select-2">
                <option value="" disabled selected>Select Topic</option>
                <option value="question">Question</option>
                <option value="audit">Free Audit</option>
              </select>
            </div>

            <div class="form-field">
              <input class="input-item" type="text" placeholder="Your Name..">
            </div>

            <div class="form-field">
              <input class="input-item" type="text" placeholder="Your email..">
            </div>

            <div class="form-field">
              <textarea class="input-body" type="text" placeholder="Your message.."></textarea>
            </div>

            <div class="form-field">
              <button class="submit">GET IN TOUCH</button>
            </div>

        </div>

      </div>

      <div class="social-media-container">
          <ul>
            <li><i class="fas fa-envelope"></i></li>
            <li><i class="fab fa-facebook-square"></i></li>
            <li><i class="fab fa-instagram"></i></li>
            <li><i class="fab fa-twitter"></i></li>
          </ul>
        </div>

    </section>

    <%= render(partial: "shared/footer") %>

  </div>

app/views/static_pages/index.html.erb
  <div class="container">
    <div class="big-header">
      
      <header>
        <figure>
          <a href="<%= root_path %>"><%= image_tag("conversion-getter-logo.png") %></a>
        </figure>
        <nav>
          <ul>
            <li><a href="<%= root_path %>">HOME</a></li>
            <li id="services-link">SERVICES</li>
            <li id="contact-link">CONTACT</li>
            <li><a href="<%= mm_path %>"><button class="m-m-btn">MODERN MARKETING</button></a></li>
            <li><button class="quote-btn">GET QUOTE</button></li>
          </ul>
        </nav>  
      </header>

      <main class="solo">
        <div class="billboard-container center">
          <h1>We Help Companies Realize Their<br>True Potential with <u>Smart Marketing</u>.</h1>
          <button class="quote-btn">GET QUOTE</button>
          <button class="audit-btn">FREE AUDIT</button>
        </div>
      </main>

    </div>

    <section class="grey-background" id="services">
      <h2>OUR MAIN MARKETING SERVICES</h2>
      <h3 class="subheadline"><i>"Our services have one thing in common — they promote growth."</i></h3>
     
      <div class="item-container">
     
        <div class="item">
          <%= image_tag("smm2.png") %>
          <h3>SOCIAL MEDIA MANAGEMENT</h3>
          <p>We help manage your social media accounts and by doing so we'll build brand awareness, and drive business — while you focus on operating your business.</p>
          <p><b>Top Features:</b></p>
          <ul> 
            <li>Social Media Audit</li>
            <li>Competitor Analysis</li>
            <li>Branding</li>
            <li>Content Creation</li>
            <li>Frequent Posting</li>
            <li>Reputation Management</li>
          </ul>
          <a href="<%= smm_path %>"><button class="read-more-btn">READ MORE</button></a>
        </div>
      
        <div class="item">
          <%= image_tag("seo2.png") %>
          <h3>SEARCH-ENGINE-OPTIMIZATION</h3>
          <p>We help optimize your website and build high-quality backlinks to increase your rankings in search engines to help people find your business organically.</p>
          <p><b>Top Features:</b></p>
          <ul> 
            <li>Website Audit</li>
            <li>Competitor Analysis</li>
            <li>Keyword Research</li>
            <li>Content Marketing</li>
            <li>On-Page Optimization</li>
            <li>Off-Page Optimization</li>
          </ul>
          <a href="<%= seo_path %>"><button class="read-more-btn">READ MORE</button></a>
        </div>
      
        <div class="item">
          <%= image_tag("ppc2.png") %>
          <h3>ADVERTISING</h3>
          <p>We help place your offer in front of the right people, with a strategy that is designed to build the tension people should feel from the absence of your product/service.</p>
          <p><b>Top Features:</b></p>
          <ul> 
            <li>Funnel Creation</li>
            <li>Ad Creation</li>
            <li>Lead Magnet Creation</li>
            <li>Landing Page Creation</li>
            <li>Email Marketing</li>
            <li>Retargeting</li>
            <li>Lookalike Audiences</li>
            <li>A/B Testing</li>
          </ul>
          <a href="<%= advertising_path %>"><button class="read-more-btn">READ MORE</button></a>
        </div>

      </div>

    </section>

    <section>
      <h2>WHY US?</h2>
      
      <div class="item-container">

        <div class="item center-item">
          <i class="fas fa-bullseye"></i>
          <h3>We Are Modern Marketers</h3>
          <p>We dive deep to understand your position in the marketplace and why people should feel the need to buy your product/service. We’re determined to cement this position of your brand in the minds of the people that you seek to serve and build the tension needed for them to take action.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-lightbulb"></i>
          <h3>We Are Innovative Marketers</h3>
          <p>We constantly seek new, better, and more efficient ways to reach the people that you seek to serve. By combining best practices and being at the forefront when it comes to the latest most innovative marketing strategies, we’ll give your brand the best opportunity to grow and reach new heights.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-heart"></i>
          <h3>We are Transparent Marketers</h3>
          <p>Our goal is to be as transparent and receptive as possible with our clients. To do that, we’ll create a marketing plan that will include the goals we agree on, the strategies we’ll use to achieve them, and the metrics we’ll use to measure the performance of our marketing efforts.</p>
        </div>

      </div>
      
    </section>


    <%= render(partial: 'shared/contactform') %>

    <%= render(partial: "shared/footer") %>

  </div> <!-- container -->

app/views/static_pages/ppc.html.erb
  <div class="container">

      <header class="blue-background">
        <figure>
          <a href="<%= root_path %>"><%= image_tag("conversion-getter-logo.png") %></a>
        </figure>
        <nav>
          <ul>
            <li><a href="<%= root_path %>">HOME</a></li>
            <li><a href="/#services">SERVICES</a></li>
            <li id="contact-link">CONTACT</li>
            <li><a href="<%= mm_path %>"><button class="m-m-btn">MODERN MARKETING</button></a></li>
            <li><button class="quote-btn">GET QUOTE</button></li>
          </ul>
        </nav>  
      </header>
    
      <section class="social-media-presentation">

        <h2>Why Do You Need an Advertising Expert?</h2>

        <p>If you are an inexperienced advertiser, it will be difficult to create a profitable advertising campaign. First of all, you lack the experience to know what works. Secondly, you don’t not know what it takes to build a funnel that converts.</p>
        
        <p>At conversiongetter, we build funnels with measurable steps, designed to build the tension people should feel from the absence of your product/service.</p>

        <p>To move people through our funnels, we incorporate advertising, lead magnets, landing pages, retargeting, and email marketing. Each campaign is carefully planned, analyzed, and optimized to get the best possible result at the lowest cost.</p>

        <button class="quote-btn">GET QUOTE</button>
        <button class="our-process-btn">OUR PROCESS</button>
        

      </section>


      <section class="grey-background" id="our-process">

        <h2>ADVERTISING</h2>
        <h3 class="subheadline">OUR PROCESS</h3>
     
      <div class="item-container">
     
        <div class="item center-item">
          <i class="fas fa-clipboard-list"></i>
          <h3>PREPARATIONS</h3>
          <p>Before we build a funnel, we'll set a clear objective for the advertising campaign. We'll also define the personas of the people that you seek to serve. These are things we’ll agree on in the marketing plan.</p>
        </div>
      
        <div class="item center-item">
          <i class="fas fa-filter"></i>
          <h3>FUNNEL</h3>
          <p>We'll build a funnel with measurable steps designed to convert the people that you seek to serve. By creating a funnel, we’ll have a clear strategic overview of the marketing activities we'll seek to turn a stranger into a customer.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-paint-brush"></i>
          <h3>AD CREATION</h3>
          <p>We'll create compelling copy that resonates with the people that you seek to serve and couple it with an image/video that will reinforce the message we want to convey.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-magnet"></i>
          <h3>LEAD MAGNET</h3>
          <p>If you have an expensive or complicated offer that requires a lot of convincing or education, we’ll create a lead magnet to get potential customers on your email list, so that we can build the tension needed to sell your product/service.</p>
        </div>
      
        <div class="item center-item">
          <i class="fas fa-code"></i>
          <h3>LANDING PAGE</h3>
          <p>We’ll create beautiful landing pages that are designed to make people take action that we seek.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-envelope"></i>
          <h3>EMAIL MARKETING</h3>
          <p>We’ll create campaigns with emails that build the tension needed for people to take action. We’ll run these campaigns simultaneously with retargeting ads, to increase the exposure of your offer during the crucial decision stage of the funnel.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-rocket"></i>
          <h3>LAUNCH</h3>
          <p>The key of building a successful advertising campaign is to test, test, and test. We’ll start small, and when we find what resonates with the audience we’re targeting — we’ll scale.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-chart-line"></i>
          <h3>OPTIMIZE</h3>
          <p>Each advertising campaign is carefully planned, analyzed, and optimized to get the best possible result at the lowest cost.</p>
        </div>

      </div>

      </section>

      <section>
      <h2>WHY US?</h2>
      
      <div class="item-container">

        <div class="item center-item">
          <i class="fas fa-bullseye"></i>
          <h3>We Are Modern Marketers</h3>
          <p>We dive deep to understand your position in the marketplace and why people should feel the need to buy your product/service. We’re determined to cement this position of your brand in the minds of the people that you seek to serve and build the tension needed for them to take action.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-lightbulb"></i>
          <h3>We Are Innovative Marketers</h3>
          <p>We constantly seek new, better, and more efficient ways to reach the people that you seek to serve. By combining best practices and being at the forefront when it comes to the latest most innovative marketing strategies, we’ll give your brand the best opportunity to grow and reach new heights.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-heart"></i>
          <h3>We are Transparent Marketers</h3>
          <p>Our goal is to be as transparent and receptive as possible with our clients. To do that, we’ll create a marketing plan that will include the goals we agree on, the strategies we’ll use to achieve them, and the metrics we’ll use to measure the performance of our marketing efforts.</p>
        </div>

      </div>
      
    </section>

    <%= render(partial: 'shared/contactform') %>

    <%= render(partial: "shared/footer") %>

  </div>

app/views/static_pages/special.html.erb
  <div class="container">     
    <div class="big-header">
      
      <header>
        <figure>
          <a href="<%= root_path %>"><%= image_tag("conversion-getter-logo.png") %></a>
        </figure>
        <nav>
          <ul>
            <li><a href="<%= root_path %>">HOME</a></li>
            <li id="services-link">SERVICES</li>
            <li id="contact-link">CONTACT</li>
            <li><a href="<%= mm_path %>"><button class="m-m-btn">MODERN MARKETING</button></a></li>
            <li><button class="quote-btn">GET QUOTE</button></li>
          </ul>
        </nav>  
      </header>

      <main class="solo">
        <div class="billboard-container center">
          <h1><span class="highlight">SPECIAL:</span> GET OUR 3 MAIN MARKETING<br> SERVICES FOR THE PRICE OF 1.</h1>
          <button class="quote-btn">GET QUOTE</button>
          <button class="audit-btn">FREE AUDIT</button>
        </div>
      </main>

    </div>
      
    <section class="grey-background" id="services">
        <div class="service-container">
          <div class="service-item">
            <h4>SERVICE #1</h4>
            <h2>ADVERTISING</h2>
             <p>We help place your offer in front of the right people, with a strategy that is designed to build the tension people should feel from the absence of your product/service.</p>
             <button class="quote-btn">GET QUOTE</button>
            <a href="<%= advertising_path %>"><button class="read-more-btn">READ MORE</button></a>
          </div>
          <div class="service-item">
            <%= image_tag("ppc-special.png") %>
          </div>
        </div>
      </section>

      <section>
        <div class="service-container">
          <div class="service-item">
            <h4>SERVICE #2</h4>
            <h2>SOCIAL MEDIA<BR>MANAGEMENT</h2>
            <p>We help manage your social media accounts and by doing so we'll build brand awareness, and drive business — while you focus on operating your business.</p>
            <button class="quote-btn">GET QUOTE</button>
            <a href="<%= smm_path %>"><button class="read-more-btn">READ MORE</button></a>
          </div>
          <div class="service-item">
            <%= image_tag("smm-special.png") %>
          </div>
        </div>
      </section>

      <section class="grey-background">
        <div class="service-container">
          <div class="service-item">
            <h4>SERVICE #3</h4>
            <h2>SEARCH-ENGINE-<BR>OPTIMIZATION</h2>
            <p>We help optimize your website and build high-quality backlinks to increase your rankings in search engines to help people find your business organically.</p>
            <button class="quote-btn">GET QUOTE</button>
            <a href="<%= seo_path %>"><button class="read-more-btn">READ MORE</button></a>
          </div>
          <div class="service-item">
            <%= image_tag("seo-special.png") %>
          </div>
        </div>
      </section>

    <section>
      <h2>WHY US?</h2>
      
      <div class="item-container">

        <div class="item center-item">
          <i class="fas fa-bullseye"></i>
          <h3>We Are Modern Marketers</h3>
          <p>We dive deep to understand your position in the marketplace and why people should feel the need to buy your product/service. We’re determined to cement this position of your brand in the minds of the people that you seek to serve and build the tension needed for them to take action.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-lightbulb"></i>
          <h3>We Are Innovative Marketers</h3>
          <p>We constantly seek new, better, and more efficient ways to reach the people that you seek to serve. By combining best practices and being at the forefront when it comes to the latest most innovative marketing strategies, we’ll give your brand the best opportunity to grow and reach new heights.</p>
        </div>

        <div class="item center-item">
          <i class="fas fa-heart"></i>
          <h3>We are Transparent Marketers</h3>
          <p>Our goal is to be as transparent and receptive as possible with our clients. To do that, we’ll create a marketing plan that will include the goals we agree on, the strategies we’ll use to achieve them, and the metrics we’ll use to measure the performance of our marketing efforts.</p>
        </div>

      </div>
      
    </section>

    <%= render(partial: 'shared/contactform') %>

<%= render(partial: "shared/footer") %>

  </div>